### ISSUE TITLE
[Feature Request] Colourisation of Output

### ISSUE THREAD

**Issue by aphirst** [tsdh/rdictcc#2]
I don't think I need to really explain what I mean by this, really. It would be nice if the output of the application were colourised, as this would make it much easier to work out at-a-glance what it is you're looking for.

I know someone that wrote their own parser for the rdictcc database files, which only worked for searching for single words, but they implemented some rudimentary colourisation. Once I'm back at my personal machine I'll see if I can post a snippet of what they did and/or a screenshot.

**Comment by tsdh** [comment]
Well, the Emacs interface does provide some colorization, the console interface not yet. What exactly would you like to be highlighted?
